//! Init command — initialize a Serena project.
//!
//! Creates `.serena/config.yaml` with default configuration
//! and `.serena/memories/` directory structure.

use std::fs;
use std::path::Path;

/// Default Serena project configuration YAML.
pub const DEFAULT_CONFIG_YAML: &str = r#"# Serena.rs — Project Configuration
# Auto-generated by `serena init`

version: "0.1.0"

# Language server protocol settings
lsp:
  enabled: true
  auto_attach: true

# Memory settings
memory:
  enabled: true
  max_memories: 100

# Tool permissions
tools:
  file_ops: true
  shell: false
  network: false
"#;

/// Initialize a Serena project at the given path.
///
/// Creates `.serena/config.yaml` and `.serena/memories/` directory.
/// Returns an error if the config file already exists (to prevent overwrite).
pub fn execute(path: &str) -> Result<(), InitError> {
    let project_dir = Path::new(path);
    let serena_dir = project_dir.join(".serena");
    let config_path = serena_dir.join("config.yaml");
    let memories_dir = serena_dir.join("memories");

    // Check if already initialized
    if config_path.exists() {
        return Err(InitError::AlreadyInitialized(config_path.to_string_lossy().to_string()));
    }

    // Create .serena/ directory
    fs::create_dir_all(&serena_dir)
        .map_err(|e| InitError::IoError(format!("failed to create .serena directory: {e}")))?;

    // Write default config
    fs::write(&config_path, DEFAULT_CONFIG_YAML)
        .map_err(|e| InitError::IoError(format!("failed to write config.yaml: {e}")))?;

    // Create memories directory
    fs::create_dir_all(&memories_dir)
        .map_err(|e| InitError::IoError(format!("failed to create memories directory: {e}")))?;

    Ok(())
}

#[derive(Debug, PartialEq)]
pub enum InitError {
    AlreadyInitialized(String),
    IoError(String),
}

impl std::fmt::Display for InitError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            InitError::AlreadyInitialized(path) => {
                write!(f, "Serena project already initialized at {path}")
            }
            InitError::IoError(msg) => write!(f, "IO error: {msg}"),
        }
    }
}

impl std::error::Error for InitError {}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    #[test]
    fn test_init_creates_serena_directory() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().to_str().unwrap();
        execute(path).unwrap();

        let serena_path = dir.path().join(".serena");
        assert!(serena_path.exists(), ".serena/ should exist");
        assert!(serena_path.is_dir(), ".serena/ should be a directory");
    }

    #[test]
    fn test_init_creates_config_yaml() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().to_str().unwrap();
        execute(path).unwrap();

        let config_path = dir.path().join(".serena").join("config.yaml");
        assert!(config_path.exists(), "config.yaml should exist");

        let content = fs::read_to_string(&config_path).unwrap();
        assert_eq!(content, DEFAULT_CONFIG_YAML, "config content should match default");
    }

    #[test]
    fn test_init_creates_memories_directory() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().to_str().unwrap();
        execute(path).unwrap();

        let memories_path = dir.path().join(".serena").join("memories");
        assert!(memories_path.exists(), ".serena/memories/ should exist");
        assert!(memories_path.is_dir(), ".serena/memories/ should be a directory");
    }

    #[test]
    fn test_init_fails_if_already_initialized() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().to_str().unwrap();

        // First init should succeed
        execute(path).unwrap();

        // Second init should fail
        let result = execute(path);
        assert!(result.is_err(), "second init should fail");
        match result.unwrap_err() {
            InitError::AlreadyInitialized(p) => {
                assert!(p.contains(".serena/config.yaml"), "error should mention config.yaml");
            }
            other => panic!("expected AlreadyInitialized, got {other:?}"),
        }
    }

    #[test]
    fn test_init_in_nonexistent_directory() {
        // A non-existent path under a temp dir — parent must exist
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("nested").join("project");
        let path_str = path.to_str().unwrap();

        let result = execute(path_str);
        assert!(result.is_ok(), "init should auto-create parent dirs");
    }
}
